version: "3.9"

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-thewind121212}/jade-fe:${IMG_TAG}
    container_name: ${FE_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: ${FE_IP}

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-thewind121212}/ciri-be:${IMG_TAG}
    container_name: ${BE_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: ${BE_IP}


networks:
  app_network:
    external: true
    name: ovh-network
